- hosts: all
  become: true
  tasks:   
    - name: Install Nginx
      yum:
        name: nginx
        state: present
     
    - name: add index.html file
      git:
        repo: git@github.com:rchincholkar/web.git
        dest: /usr/share/nginx/html/

    - name: Start Nginx
      service:
        name: nginx
        state: started
